services:
  # 10 simple backend servers, each with its own port
  backend1:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: sh -c "echo '<h1>Backend 1</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend2:
    image: nginx:alpine
    ports:
      - "3002:80"
    command: sh -c "echo '<h1>Backend 2</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend3:
    image: nginx:alpine
    ports:
      - "3003:80"
    command: sh -c "echo '<h1>Backend 3</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend4:
    image: nginx:alpine
    ports:
      - "3004:80"
    command: sh -c "echo '<h1>Backend 4</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend5:
    image: nginx:alpine
    ports:
      - "3005:80"
    command: sh -c "echo '<h1>Backend 5</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend6:
    image: nginx:alpine
    ports:
      - "3006:80"
    command: sh -c "echo '<h1>Backend 6</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend7:
    image: nginx:alpine
    ports:
      - "3007:80"
    command: sh -c "echo '<h1>Backend 7</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend8:
    image: nginx:alpine
    ports:
      - "3008:80"
    command: sh -c "echo '<h1>Backend 8</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend9:
    image: nginx:alpine
    ports:
      - "3009:80"
    command: sh -c "echo '<h1>Backend 9</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend10:
    image: nginx:alpine
    ports:
      - "3010:80"
    command: sh -c "echo '<h1>Backend 10</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
