version = "1"

[loadbalancer]
type = "network"
strategy = "round_robin"
log_level = "info" # debug, warn, error
port = 8080
max_connections = 1000
max_requests_per_connection = 100

[logging]
rotate_logs = true
log_capacity_tb = 10 
listener_address = "127.0.0.1"
path = "./log.txt"

[security]
ip_whitelist = []
ip_blacklist = []
max_request_size = 1048576  # 1 MB

[[backends]]
name = "auth service"
health_endpoint = "/healthz"
health_check_interval = 30
health_check_timeout = 5
failed_request_threshold = 5
timeout_ms = 5000
rate_limit = 400
nodes = [
    { address = "127.0.0.1:3310", weight = 2, coordinates = [35.3, 135.3] },
    { address = "127.0.0.1:3314", weight = 1, coordinates = [35.4, 135.4] }
]


[[backends]]
name = "backend2"
health_endpoint = "/healthz"
health_check_interval = 30
health_check_timeout = 5
weight = 1
circuit_breaker_threshold = 0.5
timeout_ms = 5000
rate_limit = 400
nodes = [
    { address = "http://localhost:8083", weight = 1, coordinates = [35.5, 135.5] },
    { address = "http://localhost:8084", weight = 2, coordinates = [35.6, 135.6] }
]